<?php
/**
 * @file
 * rc_drivers_links_view.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function rc_drivers_links_view_views_default_views() {
  $export = array();

  $view = new view();
	$view->name = 'driverlinks';
	$view->description = 'The links to claim a ride, and start and stop the ride';
	$view->tag = 'default, driver';
	$view->base_table = 'node';
	$view->human_name = 'DriverLinks';
	$view->core = 7;
	$view->api_version = '3.0';
	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
	
	/* Display: Master */
	$handler = $view->new_display('default', 'Master', 'default');
	$handler->display->display_options['use_more_always'] = FALSE;
	$handler->display->display_options['access']['type'] = 'role';
	$handler->display->display_options['access']['role'] = array(
		3 => '3',
		4 => '4',
		11 => '11',
	);
	$handler->display->display_options['cache']['type'] = 'none';
	$handler->display->display_options['query']['type'] = 'views_query';
	$handler->display->display_options['exposed_form']['type'] = 'basic';
	$handler->display->display_options['pager']['type'] = 'some';
	$handler->display->display_options['pager']['options']['items_per_page'] = '1';
	$handler->display->display_options['pager']['options']['offset'] = '0';
	$handler->display->display_options['style_plugin'] = 'default';
	$handler->display->display_options['row_plugin'] = 'fields';
	/* Field: Global: Custom text */
	$handler->display->display_options['fields']['nothing']['id'] = 'nothing';
	$handler->display->display_options['fields']['nothing']['table'] = 'views';
	$handler->display->display_options['fields']['nothing']['field'] = 'nothing';
	$handler->display->display_options['fields']['nothing']['label'] = '';
	$handler->display->display_options['fields']['nothing']['alter']['text'] = '<a href="/pickup"><div class="button alert radius">Available Rides</div></a>';
	$handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
	/* Sort criterion: Content: Post date */
	$handler->display->display_options['sorts']['created']['id'] = 'created';
	$handler->display->display_options['sorts']['created']['table'] = 'node';
	$handler->display->display_options['sorts']['created']['field'] = 'created';
	/* Filter criterion: Content: Published */
	$handler->display->display_options['filters']['status']['id'] = 'status';
	$handler->display->display_options['filters']['status']['table'] = 'node';
	$handler->display->display_options['filters']['status']['field'] = 'status';
	$handler->display->display_options['filters']['status']['value'] = 1;
	$handler->display->display_options['filters']['status']['group'] = 1;
	$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
	
	/* Display: Block */
	$handler = $view->new_display('block', 'Block', 'block_1');
	$handler->display->display_options['defaults']['hide_admin_links'] = FALSE;
	$handler->display->display_options['defaults']['fields'] = FALSE;
	/* Field: Global: Custom text */
	$handler->display->display_options['fields']['nothing']['id'] = 'nothing';
	$handler->display->display_options['fields']['nothing']['table'] = 'views';
	$handler->display->display_options['fields']['nothing']['field'] = 'nothing';
	$handler->display->display_options['fields']['nothing']['label'] = '';
	$handler->display->display_options['fields']['nothing']['alter']['text'] = '<br/><a href="/scheduled-rides"><div class="button secondary">Scheduled Rides</div></a><br/><br/>
	';
	$handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
	$translatables['driverlinks'] = array(
		t('Master'),
		t('more'),
		t('Apply'),
		t('Reset'),
		t('Sort by'),
		t('Asc'),
		t('Desc'),
		t('<a href="/pickup"><div class="button alert radius">Available Rides</div></a>'),
		t('Block'),
		t('<br/><a href="/scheduled-rides"><div class="button secondary">Scheduled Rides</div></a><br/><br/>
	'),
	);

  $export['thedirverlinks'] = $view;

  return $export;
}
